#!/usr/bin/env bash

export $(dbus-launch)
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P)"

#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down



#boot compton or picom if it exists
if [ -x "$(command -v compton)" ]; then
    compton &> /dev/null &
elif [ -x "$(command -v picom)" ]; then
    picom &> /dev/null &
fi

#set background
if [ -x "$(command -v feh)" ]; then
    feh --bg-fill "$SCRIPTPATH"/wallpaper.png
fi

#set the theme.toml config
leftwm-command "LoadTheme $SCRIPTPATH/theme.toml"

# Booting Polybar
pkill polybar &
pkill lemonbar &
index=0
monitor="$(polybar -m | grep +0+0 | sed s/:.*// | tac)"
leftwm-state -q -n -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d' | \
    while read -r width x y
    do
        barname="mainbar$index"
        monitor="$(polybar -m | awk -v i="$(( index + 1 ))" 'NR==i{print}' | sed s/:.*// | tr -d '\n')"
        monitor=$monitor width=$(( width - 0 )) polybar -c "$SCRIPTPATH"/polybar.config $barname &
        let index=index+1
    done
